coverage:
  status:
    project:
      default:
        target: "85%"
        threshold: "1%"
    patch:
      default:
        target: "85%"
        threshold: "5%"

ignore:
  - "test/**"
  - "scripts/**"
  - "**/*.test.ts"
  - "**/*.test.mjs"
  - "**/*.spec.ts"
