name: Build and Test

on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
        description: "Commit SHA or ref to check out"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.sha }}
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile || bun install
      - run: bun run build
      - name: Run tests with coverage
        run: bun test --coverage
      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: |
            coverage/**
          if-no-files-found: warn
