name: Build and Test

on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
        description: "Commit SHA or ref to check out"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/mcp-builder:latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.sha }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.3.1

      - name: Bun version
        run: bun --version
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build project
        run: bun run build
      - name: Run test coverage (Bun)
        run: bun run coverage
      - name: Run vice mock tests
        run: npm run test -- --platform=vice --target=mock
      - name: Run vice device tests
        run: npm run test -- --platform=vice --target=device
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          fail_ci_if_error: true
          verbose: true
