name: Build and Test

on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
        description: "Commit SHA or ref to check out"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/mcp-builder:latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.sha }}

      - name: Bun version
        run: bun --version
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build project
        run: npm run build
      - name: Run test coverage (Bun)
        run: npm run coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage/lcov.info
          if-no-files-found: warn
