name: Verify NPM Package

on:
  workflow_call:

jobs:
  verify:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/mcp-builder:latest

    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm pack --dry-run
      - run: npm run lint
      - run: npm test
